### ISSUE TITLE
Publish uwhois on pypi registry

### ISSUE THREAD

**Issue by nadouani** [Rafiot/uwhoisd#2]
Hello,

is it possible to get have the uwhois library published on PyPi registry? 
Currently, some versions of pip are not able to install the uwhois library from it's github URL.

Thanks

**Comment by Rafiot** [comment]
I'm not the maintainer of this project, so it would be better is @kgaughan would do it. Also, my branch diverged quite a lot and it desperately need some love...

**Comment by nadouani** [comment]
Yes, this makes sense, I hope @kgaughan will hear that :)

Thanks
